// <auto-generated />
using System;
using ArticleShop.Models.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArticleShop.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    [Migration("20231220083125_categorypromo")]
    partial class categorypromo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArticleShop.Models.Database.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bd7a6d0b-7b23-4cbd-a497-522228878b6f"),
                            CategoryId = new Guid("10681808-6e0d-4348-a6f7-e222bca0abf9"),
                            ExpiryDate = new DateOnly(2023, 12, 20),
                            ImagePath = "/image/no_image.jpg",
                            Name = "Chocolate bar",
                            Price = 2.34m
                        },
                        new
                        {
                            Id = new Guid("a39ad502-be57-4288-afd4-4e0d2c3373d0"),
                            CategoryId = new Guid("7333d8e5-40f4-473a-8b01-7a76662a0104"),
                            ExpiryDate = new DateOnly(2033, 12, 20),
                            ImagePath = "/image/no_image.jpg",
                            Name = "Bird cage",
                            Price = 47.29m
                        },
                        new
                        {
                            Id = new Guid("7a5d46be-4b5d-418f-b371-0713b42da82f"),
                            CategoryId = new Guid("daa1648d-7509-40dc-9b75-ed4e90072507"),
                            ExpiryDate = new DateOnly(2034, 7, 7),
                            ImagePath = "/image/no_image.jpg",
                            Name = "Flute coursebook",
                            Price = 10.00m
                        },
                        new
                        {
                            Id = new Guid("8d167375-10ab-4b4a-a7ed-563c657acae6"),
                            CategoryId = new Guid("5d2d5561-c5ea-4bbe-a588-7272a78e1fa2"),
                            ExpiryDate = new DateOnly(2043, 1, 1),
                            ImagePath = "/image/no_image.jpg",
                            Name = "Gloomhaven",
                            Price = 80.99m
                        });
                });

            modelBuilder.Entity("ArticleShop.Models.Database.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPromo")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9b0cbbcd-f7a8-4c01-ab7f-63d43c49e2c2"),
                            IsPromo = false,
                            Name = "Others"
                        },
                        new
                        {
                            Id = new Guid("10681808-6e0d-4348-a6f7-e222bca0abf9"),
                            IsPromo = false,
                            Name = "Food"
                        },
                        new
                        {
                            Id = new Guid("5d2d5561-c5ea-4bbe-a588-7272a78e1fa2"),
                            IsPromo = false,
                            Name = "Board Game"
                        },
                        new
                        {
                            Id = new Guid("10c241c9-e5af-4108-bfc6-a0d6071283ed"),
                            IsPromo = false,
                            Name = "Computer Game"
                        },
                        new
                        {
                            Id = new Guid("3cd222ae-65b0-42f5-98d2-0e44b3af3b57"),
                            IsPromo = false,
                            Name = "Book"
                        },
                        new
                        {
                            Id = new Guid("70a40bc0-f522-470e-8f78-73b7565a5fe3"),
                            IsPromo = false,
                            Name = "Furniture"
                        },
                        new
                        {
                            Id = new Guid("daa1648d-7509-40dc-9b75-ed4e90072507"),
                            IsPromo = false,
                            Name = "Music"
                        },
                        new
                        {
                            Id = new Guid("83a2355c-1392-4deb-80e8-3375954bb47a"),
                            IsPromo = false,
                            Name = "School"
                        },
                        new
                        {
                            Id = new Guid("7333d8e5-40f4-473a-8b01-7a76662a0104"),
                            IsPromo = false,
                            Name = "Animals"
                        });
                });

            modelBuilder.Entity("ArticleShop.Models.Database.Article", b =>
                {
                    b.HasOne("ArticleShop.Models.Database.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
