// <auto-generated />
using System;
using ArticleShop.Models.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArticleShop.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    [Migration("20231214195546_NonNullableImageSrc")]
    partial class NonNullableImageSrc
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArticleShop.Models.Database.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ee972760-d8c8-493e-9df3-f48411f46332"),
                            CategoryId = new Guid("67f9fcb3-69dd-4660-a4ff-3108d70d2acd"),
                            ExpiryDate = new DateOnly(2023, 12, 20),
                            ImagePath = "/image/no_image.jpg",
                            Name = "Chocolate bar",
                            Price = 2.34m
                        },
                        new
                        {
                            Id = new Guid("b534d835-40cf-4f98-af07-5971a89a05aa"),
                            CategoryId = new Guid("3d8610e3-fd6b-409f-b948-872ad71f59f5"),
                            ExpiryDate = new DateOnly(2033, 12, 20),
                            ImagePath = "/image/no_image.jpg",
                            Name = "Bird cage",
                            Price = 47.29m
                        },
                        new
                        {
                            Id = new Guid("85aebc86-e06c-4ac7-a0ea-260df74cad72"),
                            CategoryId = new Guid("caf462ec-5b6e-40fc-bdca-fdd01d137f64"),
                            ExpiryDate = new DateOnly(2034, 7, 7),
                            ImagePath = "/image/no_image.jpg",
                            Name = "Flute coursebook",
                            Price = 10.00m
                        },
                        new
                        {
                            Id = new Guid("2f8113ec-f2d7-4a69-a464-86f15664d440"),
                            CategoryId = new Guid("2099daed-67ff-4b0d-9a74-a692ffdbde55"),
                            ExpiryDate = new DateOnly(2043, 1, 1),
                            ImagePath = "/image/no_image.jpg",
                            Name = "Gloomhaven",
                            Price = 80.99m
                        });
                });

            modelBuilder.Entity("ArticleShop.Models.Database.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("358d7e61-88dd-4350-9798-cd13e41733f3"),
                            Name = "Others"
                        },
                        new
                        {
                            Id = new Guid("67f9fcb3-69dd-4660-a4ff-3108d70d2acd"),
                            Name = "Food"
                        },
                        new
                        {
                            Id = new Guid("2099daed-67ff-4b0d-9a74-a692ffdbde55"),
                            Name = "Board Game"
                        },
                        new
                        {
                            Id = new Guid("09675280-9054-4898-9da2-365262ed21a4"),
                            Name = "Computer Game"
                        },
                        new
                        {
                            Id = new Guid("87753d74-5ddb-4f27-8328-cf71aeeb9b95"),
                            Name = "Book"
                        },
                        new
                        {
                            Id = new Guid("172bccc0-2257-4088-8b78-830facaaa93c"),
                            Name = "Furniture"
                        },
                        new
                        {
                            Id = new Guid("caf462ec-5b6e-40fc-bdca-fdd01d137f64"),
                            Name = "Music"
                        },
                        new
                        {
                            Id = new Guid("96ad21ee-9d07-48bf-a17f-b76ee1968143"),
                            Name = "School"
                        },
                        new
                        {
                            Id = new Guid("3d8610e3-fd6b-409f-b948-872ad71f59f5"),
                            Name = "Animals"
                        });
                });

            modelBuilder.Entity("ArticleShop.Models.Database.Article", b =>
                {
                    b.HasOne("ArticleShop.Models.Database.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
